name: Health app E2E Tests

on:
  push:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install root dependencies
        run: npm install
      - name: Install test dependencies and run Playwright
        run: |
          cd healthapp-tests
          npm install
          npx playwright install --with-deps
          npm test